#!/bin/bash

echo "🔍 Railway Deployment Verification Script"
echo "=========================================="
echo ""

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "⚠️  Railway CLI not found. Install with: npm i -g @railway/cli"
    echo "   Then run: railway login"
    echo ""
fi

echo "📋 Required Environment Variables:"
echo ""
echo "CRITICAL:"
echo "  ✓ DATABASE_URL (auto-set by Railway PostgreSQL)"
echo "  ✓ SESSION_SECRET (must set manually)"
echo ""
echo "OPTIONAL:"
echo "  - RESEND_API_KEY (for email)"
echo "  - ANTHROPIC_API_KEY (for AI features)"
echo "  - OPENAI_API_KEY (for AI features)"
echo ""

echo "🔧 Railway Setup Steps:"
echo ""
echo "1. Add PostgreSQL Database:"
echo "   railway add --database postgresql"
echo ""
echo "2. Set SESSION_SECRET:"
echo "   railway variables --set SESSION_SECRET=\$(openssl rand -base64 32)"
echo ""
echo "3. Run Database Migrations:"
echo "   railway run npm run db:push"
echo ""
echo "4. Check Deployment Logs:"
echo "   railway logs"
echo ""
echo "5. Check Service Status:"
echo "   curl https://isohub-residualslatest2-production.up.railway.app/health"
echo ""

echo "🐛 Troubleshooting White Screen:"
echo ""
echo "1. Check Railway logs for errors:"
echo "   railway logs --tail 100"
echo ""
echo "2. Verify environment variables are set:"
echo "   railway variables"
echo ""
echo "3. Verify database connection:"
echo "   railway run node -e \"console.log(process.env.DATABASE_URL ? '✓ DATABASE_URL set' : '✗ DATABASE_URL missing')\""
echo ""
echo "4. Check if tables exist:"
echo "   railway run npm run db:push"
echo ""
